# Write your MySQL query statement below
# SELECT TD.ID
# FROM WEATHER TD
#     INNER JOIN WEATHER YD
#         ON YD.RECORDDATE = DATE_SUB(TD.RECORDDATE, INTERVAL 1 DAY)
# WHERE
#     TD.TEMPERATURE > YD.TEMPERATURE